// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_DLMtool_TMBExports
#include <TMB.hpp>
#include "LBSPR_test.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "LBSPR_test") {
    return LBSPR_test(this);
  } else {
    Rf_error("Unknown model.");
  }
  return 0;
}
